import type { Metadata } from "next";
import "./globals.css";
import Nav from '@/app/components/nav'
import Footer from '@/app/components/footer'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{children: React.ReactNode}>) {
  return (
      <html lang="en">
      <head>
          <title>{metadata.title}</title>
      </head>
      <body>
        <Nav />
        {children}
        {/*<Footer />*/}
      </body>
      </html>
  );
}
